source 'https://rubygems.org'
ruby "2.6.5"

gem 'breakpoint'
gem 'builder'
gem 'middleman', '4.1.7'
gem 'middleman-blog'
gem 'middleman-compass'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'nokogiri'
gem 'puma'
gem 'rack-contrib'
gem 'redcarpet'
gem 'slim'
